[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/web/Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/"
healthcheckTimeout = 3
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
